name: Flex
markdown: redcarpet
highlighter: true
encoding: UTF-8

# tags
collections:
  tags:
    output: true
    permalink: /tags/:path/
defaults:
  - scope:
      path: ''
      type: tags
    values:
      layout: tag