# Dependencies
markdown:         kramdown

# Permalinks
permalink:        pretty

# Setup
title:            어느 개발자의 한적한 공간
tagline:          '살아나가면서 저지른 이야기'
description:      '살아나가면서 저지른 이야기'
url:              http://closer27.github.io
highlighter:      rouge
encoding:         UTF-8
timezone:         Asia/Seoul
future:           true

author:
  name:           'Seungwon Kim'
  url:            http://closer27.github.io

# Plugins
plugins: [jekyll-paginate, jekyll-timeago]
paginate: 5
paginate_path: "/page/:num/"

# Relative time
jekyll_timeago:
  depth: 1
  today: 'today'
  yesterday: 'yesterday'
  tomorrow: 'tomorrow'
  and: 'and'
  suffix: 'ago'
  prefix: ''
  suffix_future: 'in'
  prefix_future: ''
  years: 'years'
  year: 'year'
  months: 'months'
  month: 'month'
  weeks: 'weeks'
  week: 'week'
  days: 'days'
  day: 'day'

exclude: [vendor]

# Custom vars
version:          0.9.0

github:
  repo:           https://github.com/closer27

# Tags
collections:
  tags:
    output: true
    permalink: /tags/:path/
  categories:
    output: true
    permalink: /categories/:path/

defaults:
  - scope:
      path: ''
      type: tags
    values:
      layout: tag
