# Site settings
title: Development for Seungwon
email: closer527@gmail.com
description: "for my career development, for life loggin.."
baseurl: ""
url: "http://closer27.github.io"

# Build settings
markdown: kramdown
permalink: pretty
